name: mobile
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  rxdart: ^0.23.1
  logger: ^0.6.0
  provider: ^4.0.1
  dio: ^3.0.8
  fluro: ^1.7.7
  custom_switch: ^0.0.1
  dotted_border: ^1.0.5
  intent: ^1.1.0
  camera: ^0.5.8+2
  video_player: ^0.10.11+1
  thumbnails: ^1.0.1
  path_provider:
  path:

  shared_preferences: ^0.5.6+3
  flutter_datetime_picker: ^1.3.5
  flutter_screenutil: ^1.0.2
  connectivity: ^0.4.8+2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  loading_animations: ^2.1.0
  empty_widget: ^0.0.1
  intl: ^0.16.1
  fluttertoast: ^3.0.1
  photo_view: ^0.9.2
  flutter_masked_text: ^0.8.0
  chewie: ^0.9.10
  load: ^0.1.5+1
  geolocator: ^5.3.1
  permission_handler: ^5.0.0+hotfix.3
  location: ^3.0.0
  flutter_skeleton: ^0.1.0+1
  device_info: ^0.4.2+3
  url_launcher: ^5.4.10
  export_video_frame: ^0.0.5+4
  image_picker: ^0.6.6+4
  flutter_plugin_android_lifecycle: 1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/ic_customer.png
    - assets/icons/ic_item_category.png
    - assets/icons/ic_item_customer.png
    - assets/icons/ic_item_guide.png
    - assets/icons/ic_item_profile.png
    - assets/icons/ic_profile.png
    - assets/icons/ic_setting.png
    - assets/icons/ic_home.png
    - assets/icons/ic_bell.png
    - assets/icons/ic_logo.png
    - assets/icons/ic_back.png
    - assets/icons/ic_video.png
    - assets/icons/ic_camera.png
    - assets/images/sample_avatar.png
    - assets/images/bg.png
    - assets/images/logo.png
    - assets/images/guide.png
    - assets/images/chassis_img.png
    - assets/images/car.png
    - assets/images/guild_line_new.jpg
    - assets/images/guildline_chassis_new.jpg
    - assets/icons/ic_branding.png
    - assets/icons/ic_close.png
    - assets/images/search.png
    - assets/images/thumb.png
    - assets/icons/load.png
    - assets/icons/iconCustomer.png
    - assets/icons/load@2x.png
    - assets/icons/load@3x.png
    - assets/icons/ic_exit.png
    - assets/icons/account@3x.png
    - assets/icons/password1@3x.png
    - assets/icons/password@3x.png
    - assets/icons/arrowToDetail@3x.png
    - assets/icons/wifi.png
    - assets/images/tech.jpg
    - assets/images/setting.png
    - assets/images/support.png
    - assets/images/save_ioc.png
    - assets/images/guid_create_ioc_step1.png
    - assets/images/guidline_step_2.png
    - assets/images/create_customer.png
    - assets/images/search_customer.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
